name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: curl -O "https://download.java.net/java/early_access/loom/7/openjdk-16-loom+7-285_linux-x64_bin.tar.gz"
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        version: 16
        jdkFile: ./openjdk-16-loom+7-285_linux-x64_bin.tar.gz
    - name: Run tests
      run: sbt test
